# This file is part of the OceanInsightUVVIS library https://github.com/UoMMIB/OceanInsightUVVIS/
# Copyright (C) 2021 Alex Henderson (alex.henderson@manchester.ac.uk)
# SPDX-License-Identifier: MIT

name: uvvis

channels:
    - conda-forge
    - defaults

dependencies:
    - python
    - pandas
    - pint
    - pytz
    - sphinx
    - sphinx_rtd_theme
    - myst-parser
